### ISSUE TITLE
Error: Installing kubeswitch...chown: root: illegal group name

### ISSUE THREAD

**Issue by adamzr** [ckt114/kubeswitch#3]
The README instructions say to execute: `sudo make install` when I do this on my mac I get this message:
```
Installing kubeswitch...chown: root: illegal group name
make: *** [install] Error 1
```

The tool still seems to work.

**Comment by ckt114** [comment]
@adamzr Looks like your mac doesn't have a group named `root`. I catered this Makefile w/ Linux instead of mac. I don't have a mac to test this.
