### ISSUE TITLE
Feature Request: Homebrew Distribution

### ISSUE THREAD

**Issue by adamzr** [ckt114/kubeswitch#4]
It would be easier for me if kubeswitch was available with [homebrew](https://brew.sh/) the main package manager for macOS. This way I can easily get updates and not have to build from source.

**Comment by ckt114** [comment]
@adamzr I don't use mac and don't have a mac also so I can't really do this.

**Comment by ckt114** [comment]
@adamzr I finally got a mac and did it. :D
You can install it with `brew install ckt114/tap/kubeswitch` now.
